package business;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import domain.Client;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;

public class GUIAdminClientController {
	@FXML
	private TextField tfId;
	@FXML
	private TextField tfFullName;
	@FXML
	private TextField tfPhoneNumber;
	@FXML
	private TextField tfEmail;
	@FXML
	private TextField tfDirection;
	@FXML
	private TableView tvClients;
	@FXML
	private Button btnEdit;
	@FXML
	private Button btnDelete;
	@FXML
	private Button btnReturn;
	
	private TableColumn<Client, String> tcId;
	private TableColumn<Client, String> tcFullName;
	private TableColumn<Client, Integer> tcPhoneNumber;
	private TableColumn<Client, String> tcEmail;
	private TableColumn<Client, String> tcDirection;
	
	private MyUtils utils;
	
	@FXML
	private void initialize() {
		this.utils = new MyUtils();
		initTableView();
	}
	
	private void initTableView() {
		this.tcId = new TableColumn<Client, String>("Identificacion");
		this.tcId.setCellValueFactory(new PropertyValueFactory<>("id"));
		
		this.tcFullName = new TableColumn<Client, String>("Nombre");
		this.tcFullName.setCellValueFactory(new PropertyValueFactory<>("fullName"));
		
		this.tcPhoneNumber = new TableColumn<Client, Integer>("Telefono");
		this.tcPhoneNumber.setCellValueFactory(new PropertyValueFactory<>("phoneNumber"));
		
		this.tcEmail = new TableColumn<Client, String>("Correo Electronico");
		this.tcEmail.setCellValueFactory(new PropertyValueFactory<>("email"));
		
		this.tcDirection = new TableColumn<Client, String>("Direccion");
		this.tcDirection.setCellValueFactory(new PropertyValueFactory<>("direction"));
		
		this.tvClients.getColumns().addAll(this.tcId, this.tcFullName, this.tcPhoneNumber, this.tcEmail, this.tcDirection);
		this.tvClients.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);
		
	}

	// Event Listener on Button[#btnEdit].onAction
	@FXML
	public void editClient(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnDelete].onAction
	@FXML
	public void deleteClient(ActionEvent event) {
		// TODO Autogenerated
	}
	@FXML
	public void returnMenu(ActionEvent event) {
		utils.changeView(btnEdit, "/presentation/GUIPrincipal.fxml");
	}
}
