package business;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import domain.Vehicle;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;

public class GUIAdminVehicleController {
	@FXML
	private TextField tfLicensePlate;
	@FXML
	private TextField tfBrand;
	@FXML
	private TextField tfModel;
	@FXML
	private TextField tfOwner;
	@FXML
	private ComboBox cbFuelType;
	@FXML
	private ComboBox cbYear;
	@FXML
	private TableView tvVehicles;
	@FXML
	private Button btnEdit;
	@FXML
	private Button btnDelete;
	@FXML
	private Button btnReturn;
	
	private TableColumn<Vehicle, String> tcLicensePlate;
	private TableColumn<Vehicle, String> tcBrand;
	private TableColumn<Vehicle, String> tcModel;
	private TableColumn<Vehicle, Integer> tcYear;
	private TableColumn<Vehicle, String> tcFuelType;
	private TableColumn<Vehicle, String> tcOwner;
	
	private MyUtils utils;
	
	@FXML
	private void initialize() {
		this.utils = new MyUtils();
		initTableView();
	}
	
	private void initTableView() {
		this.tcLicensePlate = new TableColumn<Vehicle, String>("Placa");
		this.tcLicensePlate.setCellValueFactory(new PropertyValueFactory<>("licensePlate"));
		
		this.tcBrand = new TableColumn<Vehicle, String>("Marca");
		this.tcBrand.setCellValueFactory(new PropertyValueFactory<>("brand"));
		
		this.tcModel = new TableColumn<Vehicle, String>("Modelo");
		this.tcModel.setCellValueFactory(new PropertyValueFactory<>("model"));
		
		this.tcYear = new TableColumn<Vehicle, Integer>("Año");
		this.tcYear.setCellValueFactory(new PropertyValueFactory<>("year"));
		
		this.tcFuelType = new TableColumn<Vehicle, String>("Tipo Combustible");
		this.tcFuelType.setCellValueFactory(new PropertyValueFactory<>("fuelType"));
		
		this.tcOwner = new TableColumn<Vehicle, String>("Dueño");
		this.tcOwner.setCellValueFactory(new PropertyValueFactory<>("owner"));
		
		this.tvVehicles.getColumns().addAll(this.tcLicensePlate, this.tcBrand, this.tcModel, this.tcYear, this.tcFuelType, this.tcOwner);
		this.tvVehicles.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);
	}

	// Event Listener on ComboBox[#cbFuelType].onAction
	@FXML
	public void loadFuels(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#cbYear].onAction
	@FXML
	public void loadYears(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnEdit].onAction
	@FXML
	public void editVehicle(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnDelete].onAction
	@FXML
	public void deleteVehicle(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnReturn].onAction
	@FXML
	public void returnMenu(ActionEvent event) {
		utils.changeView(btnEdit, "/presentation/GUIPrincipal.fxml");
	}
}
