package business;

import javafx.fxml.FXML;

import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import domain.Mechanic;
import javafx.event.ActionEvent;

import javafx.scene.control.TableView;

public class GUIAdminMechanicController {
	@FXML
	private TextField tfId;
	@FXML
	private TextField tfFullName;
	@FXML
	private ComboBox cbSpeciality;
	@FXML
	private TextField tfNumPhone;
	@FXML
	private TextField tfEmail;
	@FXML
	private TableView tvMechanics;
	@FXML
	private Button btnEdit;
	@FXML
	private Button btnDelete;
	@FXML
	private Button btnReturn;
	
	private TableColumn<Mechanic, String> tcId;
	private TableColumn<Mechanic, String> tcFullName;
	private TableColumn<Mechanic, String> tcSpecialty;
	private TableColumn<Mechanic, Integer> tcPhoneNumber;
	private TableColumn<Mechanic, String> tcEmail;
	
	private MyUtils utils;
	
	@FXML
	private void initialize() {
		this.utils = new MyUtils();
		initTableView();
	}
	
	private void initTableView() {
		this.tcId = new TableColumn<Mechanic, String>("Identificacion");
		this.tcId.setCellValueFactory(new PropertyValueFactory<>("id"));
		
		this.tcFullName = new TableColumn<Mechanic, String>("Nombre");
		this.tcFullName.setCellValueFactory(new PropertyValueFactory<>("fullName"));
		
		this.tcSpecialty = new TableColumn<Mechanic, String>("Especialidad");
		this.tcSpecialty.setCellValueFactory(new PropertyValueFactory<>("specialty"));
		
		this.tcPhoneNumber = new TableColumn<Mechanic, Integer>("Telefono");
		this.tcPhoneNumber.setCellValueFactory(new PropertyValueFactory<>("phoneNumber"));
		
		this.tcEmail = new TableColumn<Mechanic, String>("Correo Electronico");
		this.tcEmail.setCellValueFactory(new PropertyValueFactory<>("email"));
		
		this.tvMechanics.getColumns().addAll(this.tcId, this.tcFullName, this.tcSpecialty, this.tcPhoneNumber, this.tcEmail);
		this.tvMechanics.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);
		
	}

	// Event Listener on Button[#btnEdit].onAction
	@FXML
	public void editMechanic(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnDelete].onAction
	@FXML
	public void deleteMechanic(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnReturn].onAction
	@FXML
	public void returnMenu(ActionEvent event) {
		utils.changeView(btnEdit, "/presentation/GUIPrincipal.fxml");
	}
}
