package business;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.TableView;

public class GUIAdminClientController {
	@FXML
	private TextField tfId;
	@FXML
	private TextField tfFullName;
	@FXML
	private TextField tfPhoneNumber;
	@FXML
	private TextField tfEmail;
	@FXML
	private TextField tfDirection;
	@FXML
	private TableView tvClients;
	@FXML
	private Button btnEdit;
	@FXML
	private Button btnDelete;
	@FXML
	private Button btnReturn;
	private MyUtils utils;
	
	@FXML
	private void initialize() {
		this.utils = new MyUtils();
	}

	// Event Listener on Button[#btnEdit].onAction
	@FXML
	public void editClient(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnDelete].onAction
	@FXML
	public void deleteClient(ActionEvent event) {
		// TODO Autogenerated
	}
	@FXML
	public void returnMenu(ActionEvent event) {
		utils.changeView(btnEdit, "/presentation/GUIPrincipal.fxml");
	}
}
