package business;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;

import java.io.IOException;

import domain.Orders;
import domain.Services;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.control.DatePicker;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;

public class GUIAdminOrderController {
	@FXML
	private TextField tfNumOfOrder;
	@FXML
	private DatePicker dpCreationDate;
	@FXML
	private ComboBox cbMechanicSelected;
	@FXML
	private TableView tvOrders;
	@FXML
	private TableView tvServices;
	@FXML
	private ComboBox cbServiceSelected;
	@FXML
	private TextField tfTotalPrice;
	@FXML
	private Button btnRemoveService;
	@FXML
	private TextField tfOservation;
	@FXML
	private Button btnReturn;
	@FXML
	private ComboBox<String> cbStateOrder;
	@FXML
	private Button btnEdit;
	@FXML
	private Button btnDelete;
	
	private TableColumn<Orders, Integer> tcOrderNumber;
	private TableColumn<Orders, String> tcCreationDate;
	private TableColumn<Orders, String> tcOrderState;
	private TableColumn<Orders, String> tcObservations;
	private TableColumn<Orders, Integer> tcTotalPrice;
	
	private TableColumn<Services, Integer> tcServiceCode;
	private TableColumn<Services, String> tcServiceName;
	private TableColumn<Services, String> tcDescription;
	private TableColumn<Services, Integer> tcBaseCost;
	private TableColumn<Services, Integer> tcEstimatedTime;

	private MyUtils utils;
	
	@FXML
	private void initialize() {
		this.utils = new MyUtils();
		initTableView();
		String [] orderStates = {"Registrada", "En proceso", "Completada", "Entregada", "Cancelada"};
		cbStateOrder.getItems().addAll(orderStates);
	}
	
	private void initTableView() {
		this.tcOrderNumber = new TableColumn<Orders, Integer>("Num Orden");
		this.tcOrderNumber.setCellValueFactory(new PropertyValueFactory<>("orderNumber"));
		
		this.tcCreationDate = new TableColumn<Orders, String>("Fecha Creacion");
		this.tcCreationDate.setCellValueFactory(new PropertyValueFactory<>("creationDate"));
		
		this.tcOrderState = new TableColumn<Orders, String>("Estado");
		this.tcOrderState.setCellValueFactory(new PropertyValueFactory<>("orderState"));
		
		this.tcObservations = new TableColumn<Orders, String>("Observaciones");
		this.tcObservations.setCellValueFactory(new PropertyValueFactory<>("observations"));
		
		this.tcTotalPrice = new TableColumn<Orders, Integer>("Precio Total");
		this.tcTotalPrice.setCellValueFactory(new PropertyValueFactory<>("totalPrice"));
		
		this.tvOrders.getColumns().addAll(this.tcOrderNumber, this.tcCreationDate, this.tcOrderState, this.tcObservations, this.tcTotalPrice);
		this.tvOrders.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);
		
		this.tcServiceCode = new TableColumn<Services, Integer>("Codigo");
		this.tcServiceCode.setCellValueFactory(new PropertyValueFactory<>("serviceCode"));
		
		this.tcServiceName = new TableColumn<Services, String>("Nombre");
		this.tcServiceName.setCellValueFactory(new PropertyValueFactory<>("serviceName"));
		
		this.tcDescription = new TableColumn<Services, String>("Descripcion");
		this.tcDescription.setCellValueFactory(new PropertyValueFactory<>("description"));
		
		this.tcBaseCost = new TableColumn<Services, Integer>("Costo Base");
		this.tcBaseCost.setCellValueFactory(new PropertyValueFactory<>("baseCost"));
		
		this.tcEstimatedTime = new TableColumn<Services, Integer>("Tiempo Estimado(Horas)");
		this.tcEstimatedTime.setCellValueFactory(new PropertyValueFactory<>("estimatedTime"));
		
		this.tvServices.getColumns().addAll(this.tcServiceCode, this.tcServiceName, this.tcDescription, this.tcBaseCost, this.tcEstimatedTime);
		this.tvServices.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);
	}
	
	// Event Listener on Button[#btnRemoveService].onAction
	@FXML
	public void removeService(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCancel].onAction
	@FXML
	public void returnMenu(ActionEvent event) {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/GUIPrincipal.fxml"));
			Parent root = loader.load();	
			utils.changeView(btnEdit, root);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#btnEdit].onAction
	@FXML
	public void editOrder(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnDelete].onAction
	@FXML
	public void deleteOrder(ActionEvent event) {
		// TODO Autogenerated
	}
}
