package business;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.stage.FileChooser;

import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import java.util.LinkedList;
import java.util.List;

import data.MechanicData;
import data.OrdersData;
import data.ServicesData;
import data.VehicleData;
import domain.Mechanic;
import domain.Orders;
import domain.Services;
import domain.Vehicle;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;
import javafx.scene.control.TableColumn;
import javafx.scene.control.ComboBox;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.DatePicker;

import javafx.scene.control.TableView;

public class GUIAdminOrdersController {
	@FXML
	private TextField tfNumOfOrder;
	@FXML
	private DatePicker dpCreationDate;
	@FXML
	private ComboBox<Mechanic> cbMechanics;
	@FXML
	private TableView<Orders> tvOrders;
	@FXML
	private TableView<Services> tvServices;
	@FXML
	private ComboBox<Services> cbServices;
	@FXML
	private TextField tfTotalPrice;
	@FXML
	private Button btnRemoveService;
	@FXML
	private TextField tfOservation;
	@FXML
	private Button btnReturn;
	@FXML
	private ComboBox<String> cbStateOrder;
	@FXML
	private Button btnEdit;
	@FXML
	private Button btnDelete;
	@FXML
	private Button btnAddPhotos;
	@FXML
	private Label lbStateVehicle;
	
	private TableColumn<Orders, Integer> tcOrderNumber;
	private TableColumn<Orders, String> tcCreationDate;
	private TableColumn<Orders, String> tcOrderState;
	private TableColumn<Orders, String> tcObservations;
	private TableColumn<Orders, Integer> tcTotalPrice;
	
	private TableColumn<Services, Integer> tcServiceCode;
	private TableColumn<Services, String> tcServiceName;
	private TableColumn<Services, String> tcDescription;
	private TableColumn<Services, Integer> tcBaseCost;
	private TableColumn<Services, Integer> tcEstimatedTime;
	
	private MyUtils utils;
	private OrdersData orderData;
	private ServicesData serviceData;
	private MechanicData mechanicData;
	private VehicleData vehicleData;
	
	LinkedList<Services> servicesOnTable;
	private int price;
	
	@FXML
	private void initialize() {
		this.utils = new MyUtils();
		this.orderData = new OrdersData();
		this.serviceData = new ServicesData();
		this.mechanicData = new MechanicData();
		this.vehicleData = new VehicleData();
		this.servicesOnTable = new LinkedList<Services>();
		
		initTableViews();
		fillCbMechanics();
		fillCbServices();
		fillCbOrderState();
		setTableOrders();
	}

	// Event Listener on TableView[#tvOrders].onMouseClicked
	@FXML
	public void selectOrder(MouseEvent event) {
		Orders order = OrderSelectedTV();
		if(order != null) {
			int idMechanic = order.getIdMechanic();
			Mechanic mechanic = searchMechanic(idMechanic);
			tfNumOfOrder.setText(String.valueOf(order.getOrderNumber()));
			tfOservation.setText(order.getObservations());
			tfTotalPrice.setText(String.valueOf(order.getTotalPrice()));
			price = order.getTotalPrice();
			dpCreationDate.setValue(order.getCreationDate());
			cbMechanics.setValue(mechanic);
			cbStateOrder.setValue(order.getOrderState());
			LinkedList<Services> services = orderData.listServicesByOrder(order.getId());
			servicesOnTable.clear();
			for(Services tempService : services) {
				servicesOnTable.add(tempService);
			}
			setDataTableViewServices();
			int idVehicle = order.getIdVehicle();
			Vehicle vehicle = searchVehicle(idVehicle);
			if(vehicle.getState().equalsIgnoreCase("Activo")) {
				lbStateVehicle.setText("ESTADO DEL VEHICULO ASOCIADO: ACTIVO");
			} else if(vehicle.getState().equalsIgnoreCase("Eliminado")) {
				lbStateVehicle.setText("ESTADO DEL VEHICULO ASOCIADO: ELIMINADO");
			}
		}
	}
	
	// Event Listener on TableView[#tvServices].onMouseClicked
	@FXML
	public void selectService(MouseEvent event) {
		// TODO Autogenerated
	}
	
	// Event Listener on Button[#btnRemoveService].onAction
	@FXML
	public void removeService(ActionEvent event) {
		Services serviceSelected = tvServices.getSelectionModel().getSelectedItem();
		if (serviceSelected == null) {
			LogicAlert.alertMessage("Debe Seleccionar un Servicio en la Tabla Para Eliminarlo");
			return;
		}
		servicesOnTable.remove(serviceSelected);
		price -= serviceSelected.getBaseCost();
		tfTotalPrice.setText(String.valueOf(price));
		setDataTableViewServices();
	}
	
	// Event Listener on Button[#btnReturn].onAction
	@FXML
	public void returnMenu(ActionEvent event) {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/GUIPrincipal.fxml"));
			Parent root = loader.load();	
			utils.changeView(btnReturn, root);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
	
	// Event Listener on Button[#btnEdit].onAction
	@FXML
	public void editOrder(ActionEvent event) {
		Orders order = OrderSelectedTV();
		if(order == null) {
			LogicAlert.alertMessage("Debe Seleccionar una Orden en la Tabla");
			return;
		}
		if(validForm()) {
			return;
		} else {
			int idOrder = order.getId();
			int orderNumber = order.getOrderNumber();
			Mechanic mechanic = cbMechanics.getSelectionModel().getSelectedItem();
			String orderState = cbStateOrder.getValue();
			LocalDate creationDate = dpCreationDate.getValue();
			String observations = tfOservation.getText();
			int totalPrice = Integer.parseInt(tfTotalPrice.getText());
			int idMechanic = mechanic.getId();
			int idVehicle = order.getIdVehicle();
			if(orderData.updateOrder(orderNumber, orderState, observations, totalPrice, creationDate, idVehicle, idMechanic)) {
				LogicAlert.alertMessage("Orden Actualizada Correctamente!!");
				serviceData.deleteServicesToOrder(idOrder);
				for(Services temp : servicesOnTable) {
					serviceData.addServiceToOrder(idOrder, temp.getId());
				}
				clearForm();
				setTableOrders();
			}
		}
	}
	
	@FXML
	public void addService(ActionEvent event) {
		Services serviceSelected = cbServices.getValue();
		if(serviceSelected == null) {
			LogicAlert.alertMessage("Debe Seleccionar un Servicio");
			return;
		}
		for(Services temp : servicesOnTable) {
			if(temp.getId() == serviceSelected.getId()) {
				LogicAlert.alertMessage("El Servicio ya Está Agregado");
				return;
			}
		}
		servicesOnTable.add(serviceSelected);
	    price += serviceSelected.getBaseCost();
	    tfTotalPrice.setText(String.valueOf(price));
	    setDataTableViewServices();
	}
	
	// Event Listener on Button[#btnDelete].onAction
	@FXML
	public void deleteOrder(ActionEvent event) {
		Orders order = OrderSelectedTV();
		if(order == null) {
			LogicAlert.alertMessage("Debe Seleccionar una Orden en la Tabla");
			return;
		}
		if(orderData.deleteOrder(order.getId())) {
			LogicAlert.alertMessage("Orden Eliminada Correctamente");
			clearForm();
			setTableOrders();
		}
	}
	
	@FXML
	public void addPhotos(ActionEvent event) {
		Orders order = OrderSelectedTV();
		
		if (order == null) {
			LogicAlert.alertMessage("Debe seleccionar una orden");
			return;
		}
		
		int idVehicle = order.getIdVehicle();
		Vehicle vehicle = searchVehicle(idVehicle);
		
		if (vehicle == null) {
			LogicAlert.alertMessage("No se encontro el vehiculo");
			return;
		}
		
		String licensePlate = vehicle.getLicensePlate();
		FileChooser fileChooser = new FileChooser();
		fileChooser.setTitle("Agregar Fotos");
		
		fileChooser.getExtensionFilters().addAll(
			new FileChooser.ExtensionFilter("Imagenes", "*.png", "*.jpg", "*.jpeg", "*.gif"),
			new FileChooser.ExtensionFilter("PNG", "*.png"),
			new FileChooser.ExtensionFilter("JPEG", "*.jpg", "*.jpeg"),
			new FileChooser.ExtensionFilter("Todos", "*.*")
		);
		
		List<File> files = fileChooser.showOpenMultipleDialog(btnAddPhotos.getScene().getWindow());
		
		if (files != null && !files.isEmpty()) {
			uploadImages(licensePlate, files);
		}
	}
	
	private void uploadImages(String licensePlate, List<File> files) {
		try {
			ClientAdminAutoTech client = getAdminClient();
			int uploadedCount = 0;
			
			for (File imageFile : files) {
				if (imageFile.length() > 5 * 1024 * 1024) {
					LogicAlert.alertMessage("Imagen muy grande: " + imageFile.getName());
					continue;
				}
				client.uploadVehicleImage(licensePlate, imageFile);
				uploadedCount++;
			}
			
			if (uploadedCount > 0) {
				LogicAlert.alertMessage("Se agregaron " + uploadedCount + " fotos");
			}
			
		} catch (Exception e) {
			LogicAlert.alertMessage("Error: " + e.getMessage());
			e.printStackTrace();
		}
	}
	
	private ClientAdminAutoTech getAdminClient() {
		return Main.getAdminClient();
	}
	
	private void initTableViews() {
		this.tcOrderNumber = new TableColumn<Orders, Integer>("Num Orden");
		this.tcOrderNumber.setCellValueFactory(new PropertyValueFactory<>("orderNumber"));
		
		this.tcCreationDate = new TableColumn<Orders, String>("Fecha Creacion");
		this.tcCreationDate.setCellValueFactory(new PropertyValueFactory<>("creationDate"));
		
		this.tcOrderState = new TableColumn<Orders, String>("Estado");
		this.tcOrderState.setCellValueFactory(new PropertyValueFactory<>("orderState"));
		
		this.tcObservations = new TableColumn<Orders, String>("Observaciones");
		this.tcObservations.setCellValueFactory(new PropertyValueFactory<>("observations"));
		
		this.tcTotalPrice = new TableColumn<Orders, Integer>("Precio Total");
		this.tcTotalPrice.setCellValueFactory(new PropertyValueFactory<>("totalPrice"));
		
		this.tvOrders.getColumns().addAll(this.tcOrderNumber, this.tcCreationDate, this.tcOrderState, this.tcObservations, this.tcTotalPrice);
		this.tvOrders.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);
		
		this.tcServiceCode = new TableColumn<Services, Integer>("Codigo");
		this.tcServiceCode.setCellValueFactory(new PropertyValueFactory<>("serviceCode"));
		
		this.tcServiceName = new TableColumn<Services, String>("Nombre");
		this.tcServiceName.setCellValueFactory(new PropertyValueFactory<>("serviceName"));
		
		this.tcDescription = new TableColumn<Services, String>("Descripcion");
		this.tcDescription.setCellValueFactory(new PropertyValueFactory<>("description"));
		
		this.tcBaseCost = new TableColumn<Services, Integer>("Costo Base");
		this.tcBaseCost.setCellValueFactory(new PropertyValueFactory<>("baseCost"));
		
		this.tcEstimatedTime = new TableColumn<Services, Integer>("Tiempo Estimado(Horas)");
		this.tcEstimatedTime.setCellValueFactory(new PropertyValueFactory<>("estimatedTime"));
		
		this.tvServices.getColumns().addAll(this.tcServiceCode, this.tcServiceName, this.tcDescription, this.tcBaseCost, this.tcEstimatedTime);
		this.tvServices.setColumnResizePolicy(TableView.CONSTRAINED_RESIZE_POLICY);
	}
	
	private void setTableOrders() {
		LinkedList<Orders> orders = orderData.getListOrders();
		ObservableList<Orders> observable = FXCollections.observableArrayList(orders);
		tvOrders.setItems(observable);
	}
	
	private Orders OrderSelectedTV() {
		Orders tempOrder = this.tvOrders.getSelectionModel().getSelectedItem();
		return tempOrder;
	}
	
	private Mechanic searchMechanic(int idMechanic) {
		LinkedList<Mechanic> mechanics = mechanicData.getListMechanics();
		for(Mechanic tempMechanic : mechanics) {
			if(tempMechanic.getId() == idMechanic) {
				return tempMechanic;
			}
		}
		return null;
	}
	
	private Vehicle searchVehicle(int idVehicle) {
		LinkedList<Vehicle> vehicles = vehicleData.getListVehicles();
		for(Vehicle tempVehicle : vehicles) {
			if(tempVehicle.getId() == idVehicle) {
				return tempVehicle;
			}
		}
		return null;
	}
	
	private void fillCbServices() {
		LinkedList<Services> services = serviceData.getListServicesActive();
		cbServices.getItems().addAll(services);
	}
	
	private void fillCbMechanics() {
		LinkedList<Mechanic> mechanics = mechanicData.getListMechanics();
		cbMechanics.getItems().addAll(mechanics);
	}
	
	private void fillCbOrderState() {
		String [] orderStates = {"Registrada", "En proceso", "Completada", "Cancelada"};
		cbStateOrder.getItems().addAll(orderStates);
	}
	
	private void setDataTableViewServices() {
		ObservableList<Services> observable = FXCollections.observableArrayList(servicesOnTable);
		tvServices.setItems(observable);
	}
	
	private void clearForm() {
		tfNumOfOrder.clear();
		tfOservation.clear();
		tfTotalPrice.clear();
		cbMechanics.setValue(null);
		cbServices.setValue(null);
		dpCreationDate.setValue(null);
		servicesOnTable.clear();
		tvOrders.getSelectionModel().clearSelection();
		tvServices.getSelectionModel().clearSelection();
		setDataTableViewServices();
	}
	
	private boolean validForm() {
		if(dpCreationDate.getValue() == null) {
			LogicAlert.alertMessage("Debe seleccionar una fecha");
			return true;
		}
		if(cbMechanics.getValue() == null) {
			LogicAlert.alertMessage("Debe seleccionar un mecánico");
			return true;
		}
		if(tfOservation.getText().isBlank()) {
			LogicAlert.alertMessage("Debe dejar una observación");
			return true;
		}
		if(dpCreationDate.getValue().isAfter(LocalDate.now())) {
			LogicAlert.alertMessage("La fecha no puede ser mayor al día actual");
			return true;
		}
		if(cbStateOrder.getValue() == null) {
			LogicAlert.alertMessage("Debe Seleccionar un Estado");
			return true;
		}
		return false;
	}
}