package business;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class GUIClientController {
	@FXML
	private TextField tfId;
	@FXML
	private Button btnAddClient;
	@FXML
	private Button btnEditClient;
	@FXML
	private Button btnDeleteClient;
	@FXML
	private Button btnShowListClient;
	@FXML
	private Button btnReturn;
	@FXML
	private TextField tfFullName;
	@FXML
	private TextField tfPhoneNumber;
	@FXML
	private TextField tfEmail;
	@FXML
	private TextField tfDirection;
	private MyUtils utils;
	
	@FXML
	private void initialize() {
		this.utils = new MyUtils();
	}

	// Event Listener on Button[#btnAddClient].onAction
	@FXML
	public void addClient(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnEditClient].onAction
	@FXML
	public void editClient(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnDeleteClient].onAction
	@FXML
	public void deleteClient(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnShowListClient].onAction
	@FXML
	public void showListClient(ActionEvent event) {
		// TODO Autogenerated
	}
	@FXML
	public void returnPrincipalMenu(ActionEvent event) {
		utils.changeView(btnAddClient, "/presentation/GUIPrincipal.fxml");
	}
}
