package business;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

public class GUIMechanicController {
	@FXML
	private TextField tfFullName;
	@FXML
	private TextField tfPhoneNumber;
	@FXML
	private TextField tfEmail;
	@FXML
	private Button btnAddMechanic;
	@FXML
	private Button btnEditMechanic;
	@FXML
	private Button btnDeleteMechanic;
	@FXML
	private Button btnShowListMechanic;
	@FXML
	private ComboBox cbSpecialty;

	// Event Listener on Button[#btnAddMechanic].onAction
	@FXML
	public void addMechanic(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnEditMechanic].onAction
	@FXML
	public void editMechanic(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnDeleteMechanic].onAction
	@FXML
	public void deleteMechanic(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnShowListMechanic].onAction
	@FXML
	public void showListMechanic(ActionEvent event) {
		// TODO Autogenerated
	}
}
