package business;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

public class GUIMechanicController {
	@FXML
	private TextField tfFullName;
	@FXML
	private TextField tfPhoneNumber;
	@FXML
	private TextField tfEmail;
	@FXML
	private Button btnAddMechanic;
	@FXML
	private Button btnReturn;
	@FXML
	private Button btnShowListMechanic;
	@FXML
	private ComboBox cbSpecialty;
	private MyUtils utils;
	
	@FXML
	private void initialize() {
		this.utils = new MyUtils();
	}

	// Event Listener on Button[#btnAddMechanic].onAction
	@FXML
	public void addMechanic(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnEditMechanic].onAction
	@FXML
	public void returnMenu(ActionEvent event) {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/GUIPrincipal.fxml"));
			Parent root = loader.load();	
			utils.changeView(btnReturn, root);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#btnShowListMechanic].onAction
	@FXML
	public void showListMechanic(ActionEvent event) {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/GUIAdminMechanic.fxml"));
			Parent root = loader.load();	
			utils.changeView(btnAddMechanic, root);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}
