package business;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.control.DatePicker;

import javafx.scene.control.TableView;

public class GUIOrdersController {
	@FXML
	private TextField tfNumOfOrder;
	@FXML
	private DatePicker dpCreationDate;
	@FXML
	private TextField tfOrderState;
	@FXML
	private ComboBox cbMechanicSelected;
	@FXML
	private TableView tvVehicle;
	@FXML
	private TableView tvServices;
	@FXML
	private ComboBox cbServiceSelected;
	@FXML
	private TextField tfTotalPrice;
	@FXML
	private Button btnRemoveService;
	@FXML
	private TextField tfOservation;
	@FXML
	private Button btnRegisterOrder;
	@FXML
	private Button btnCancel;
	
	private MyUtils utils;
	
	@FXML
	private void initialize() {
		this.utils = new MyUtils();
	}

	// Event Listener on Button[#btnRemoveService].onAction
	@FXML
	public void removeService(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnRegisterOrder].onAction
	@FXML
	public void addOrder(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnCancel].onAction
	@FXML
	public void cancelRegister(ActionEvent event) {
		utils.changeView(btnRemoveService, "/presentation/GUIPrincipal.fxml");
	}
}
