package business;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class GUIPrincipalController {
	@FXML
	private Button btnClient;
	@FXML
	private Button btnVehicle;
	@FXML
	private Button btnMechanic;
	@FXML
	private Button btnService;
	@FXML
	private Button btnOrders;
	@FXML
	private Button btnReport;
	
	private MyUtils utils;
	
	@FXML
	private void initialize() {
		this.utils = new MyUtils();
		
	}

	// Event Listener on Button[#btnClient].onAction
	@FXML
	public void showGUIClient(ActionEvent event) {
		utils.changeView(btnClient, "/presentation/GUIClient.fxml");
	}
	// Event Listener on Button[#btnVehicle].onAction
	@FXML
	public void showGUIVehicle(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnMechanic].onAction
	@FXML
	public void showGUIMechanic(ActionEvent event) {
		utils.changeView(btnClient, "/presentation/GUIMechanic.fxml");
	}
	// Event Listener on Button[#btnService].onAction
	@FXML
	public void showGUIService(ActionEvent event) {
		utils.changeView(btnClient, "/presentation/GUIService.fxml");
	}
	// Event Listener on Button[#btnOrders].onAction
	@FXML
	public void showGUIOrders(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnReport].onAction
	@FXML
	public void showGUIReport(ActionEvent event) {
		// TODO Autogenerated
	}
}
