package business;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.control.Button;

import java.io.IOException;

import javafx.event.ActionEvent;

public class GUIPrincipalController {
	@FXML
	private Button btnClient;
	@FXML
	private Button btnVehicleAdministration;
	@FXML
	private Button btnMechanic;
	@FXML
	private Button btnService;
	@FXML
	private Button btnClientAdmin;
	@FXML
	private Button btnOrdersAdministration;
	@FXML
	private Button btnReport;
	private MyUtils utils;
	
	@FXML
	private void initialize() {
		this.utils = new MyUtils();
	}

	// Event Listener on Button[#btnClient].onAction
	@FXML
	public void showGUIClient(ActionEvent event) {
		
		if (utils.verifyServices()) {	
			LogicAlert.alertMessage("Primero debe de agregar un servicio");
		}else {
			try {
				FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/GUIClient.fxml"));
				Parent root = loader.load();	
				utils.changeView(btnClient, root);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
	}
	// Event Listener on Button[#btnVehicleAdministration].onAction
	@FXML
	public void showAdministrationVehicle(ActionEvent event) {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/GUIAdminVehicle.fxml"));
			Parent root = loader.load();	
			GUIOrdersController ordersController = loader.getController();		
		
			utils.changeView(btnClient, root);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#btnMechanic].onAction
	@FXML
	public void showGUIMechanic(ActionEvent event) {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/GUIMechanic.fxml"));
			Parent root = loader.load();	
			utils.changeView(btnMechanic, root);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#btnService].onAction
	@FXML
	public void showGUIService(ActionEvent event) {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/GUIService.fxml"));
			Parent root = loader.load();	
			utils.changeView(btnService, root);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#btnOrdersAdministration].onAction
	@FXML
	public void showAdministrationOrder(ActionEvent event) {
		try {
			FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/GUIAdminOrder.fxml"));
			Parent root = loader.load();	
			utils.changeView(btnClient, root);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	// Event Listener on Button[#btnReport].onAction
	@FXML
	public void showGUIReport(ActionEvent event) {
		// TODO Autogenerated
	}
	@FXML
	public void showAdminClient(ActionEvent event) {
		if (utils.verifyServices()) {
			LogicAlert.alertMessage("Primero debe de agregar un servicio");
		}else {
			try {
				FXMLLoader loader = new FXMLLoader(getClass().getResource("/presentation/GUIAdminClient.fxml"));
				Parent root = loader.load();	
				utils.changeView(btnClientAdmin, root);
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}
}
