package business;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class GUIPrincipalController {
	@FXML
	private Button btnClient;
	@FXML
	private Button btnVehicleAdministration;
	@FXML
	private Button btnMechanic;
	@FXML
	private Button btnService;
	@FXML
	private Button btnClientAdmin;
	@FXML
	private Button btnOrdersAdministration;
	@FXML
	private Button btnReport;
	private MyUtils utils;
	
	@FXML
	private void initialize() {
		this.utils = new MyUtils();
	}

	// Event Listener on Button[#btnClient].onAction
	@FXML
	public void showGUIClient(ActionEvent event) {
		utils.changeView(btnClient, "/presentation/GUIClient.fxml");
	}
	// Event Listener on Button[#btnVehicleAdministration].onAction
	@FXML
	public void showAdministrationVehicle(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnMechanic].onAction
	@FXML
	public void showGUIMechanic(ActionEvent event) {
		utils.changeView(btnClient, "/presentation/GUIMechanic.fxml");
	}
	// Event Listener on Button[#btnService].onAction
	@FXML
	public void showGUIService(ActionEvent event) {
		utils.changeView(btnClient, "/presentation/GUIService.fxml");
	}
	// Event Listener on Button[#btnOrdersAdministration].onAction
	@FXML
	public void showAdministrationOrder(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnReport].onAction
	@FXML
	public void showGUIReport(ActionEvent event) {
		// TODO Autogenerated
	}
	@FXML
	public void showAdminClient(ActionEvent event) {
		utils.changeView(btnClient, "/presentation/GUIAdminClient.fxml");
	}
}
