package business;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.TextArea;

import javafx.scene.control.ComboBox;

public class GUIReportsController {
	@FXML
	private TextArea taResults;
	@FXML
	private ComboBox cbData;
	@FXML
	private TextField tfData;
	@FXML
	private Button btnSearch;

	// Event Listener on Button[#btnSearch].onAction
	@FXML
	public void search(ActionEvent event) {
		// TODO Autogenerated
	}
}
