package business;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

public class GUIServiceController {
	@FXML
	private TextField tfServiceCode;
	@FXML
	private TextField tfServiceName;
	@FXML
	private TextField tfDescription;
	@FXML
	private TextField tfBaseCost;
	@FXML
	private TextField tfEstimatedTime;
	@FXML
	private Button btnAddService;
	@FXML
	private Button btnEditService;
	@FXML
	private Button btnDeleteService;
	@FXML
	private Button btnShowListService;
	@FXML
	private Button btnReturnMenu;
	
	private MyUtils utils;
	
	@FXML
	private void initialize() {
		this.utils = new MyUtils();
		
	}

	// Event Listener on Button[#btnAddService].onAction
	@FXML
	public void addService(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnEditService].onAction
	@FXML
	public void editService(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnDeleteService].onAction
	@FXML
	public void deleteService(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnShowListService].onAction
	@FXML
	public void showListService(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnReturnMenu].onAction
	@FXML
	public void returnMenu(ActionEvent event) {
		utils.changeView(btnAddService, "/presentation/GUIPrincipal.fxml");
	}
}
